### ISSUE TITLE
转换权重模型失败

### ISSUE THREAD

**Issue by cxumol** [JunnYu/RWKV-v2-RNN-paddle#1]
环境
- ubuntu 18.04
- cuda 11.2
- python 3.9.7
- pytorch 1.8.0
- paddlepaddle 2.4.1

RWKV 权重模型
https://github.com/BlinkDL/AI-Writer/releases/tag/v2022-02-15

```bash
~/share/RWKV-v2-RNN-paddle# python convert.py
```

```python-traceback
Compiling user custom op, it will cost a few seconds.....
2023-01-28 14:38:08,733 - INFO - Re-Compiling timex.so, because specified cflags have been changed. New signature c5df045d0d8250bc5fb4e54947873855 has been saved into /root/.cache/paddle_extensions/timex/version.txt.
[2023-01-28 14:38:08,733] [    INFO] extension_utils.py:1238 - Re-Compiling timex.so, because specified cflags have been changed. New signature c5df045d0d8250bc5fb4e54947873855 has been saved into /root/.cache/paddle_extensions/timex/version.txt.
Traceback (most recent call last):
  File "/root/share/RWKV-v2-RNN-paddle/convert.py", line 36, in <module>
    convert_pytorch_checkpoint_to_paddle(
  File "/root/share/RWKV-v2-RNN-paddle/convert.py", line 15, in convert_pytorch_checkpoint_to_paddle
    pytorch_state_dict = pytorch_state_dict.state_dict()
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1455, in state_dict
    return self._state_dict_impl(
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1370, in _state_dict_impl
    if buffer is not None and name not in self._non_persistable_buffer_names_set:
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1144, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GPT' object has no attribute '_non_persistable_buffer_names_set'
```

**Comment by cxumol** [comment]
找到了应该用这个
https://github.com/JunnYu/Paddle-AI-Writer/blob/dev/paddle_src/convert_pytorch2paddle.py
